version: '3'

services:
  database:
    image: 'postgres:14.4-alpine3.16'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=app
    volumes:
      - './prisma/data:/var/lib/postgresql/data'
    networks:
      - cb-network

networks:
  cb-network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local